# .github/workflows/check-source-branch.yml
name: Check PR source branch

on:
  pull_request:
    branches: [main]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR is from dev
        if: github.head_ref != 'dev'
        run: |
          echo "Pull request to main must originate from dev (curent branch : ${{ github.head_ref }})"
          exit 1