"""
Parsing utils: dataframes check, parser helpers
"""

__authors__ = ("Enki SAURA")
__contact__ = ("esaura@ikosconsulting.com")
__copyright__ = "IKOS"
__date__ = "18/02/2025"
__version__ = "0.0.1"

import pandas as pd
import numpy as np
import json
import time
import hashlib
import os
import tempfile
import zipfile
from pathlib import Path
import requests
import warnings
from typing import Callable, Literal

from bits.src import parse

# Different possible naming that can be found elsewhere to refer to the GNSS constellations. Case is ignored.
gnss_id_variants = {
    "gps": ["gps", "g", "l", "l1", "l2", "l5", "navstar", "gps-iii", "gps-g", "navstar gps",],
    "glo": [ "glonass", "glo", "r", "r1",],
    "gal": [ "galileo", "gal", "e", "e1", "e2", "e3", "e3a", "e3b",],
    "bei": [ "beidou", "compass", "bds", "bei", "b", "c", "b1", "b2", "b3",],
}


def normalize_gnss_constellation(name: str) -> str:
    """
    This function takes a constellation name and converts it to its normalized name, regardless of the format used, and
    ignoring case.

    Inside BITS, GNSS constellations should be referred as:
    GPS -> "gps"
    Galileo -> "gal"
    Glonass -> "glo"
    Beidou -> "bei"

    :param name: not normalized GNSS constellation name
    :return: BITS normalized GNSS constellation name
    """
    # Convert the input name to lowercase for case-insensitive comparison
    lower_name = name.strip().lower()

    # If the name matches any of the GNSS variants, return its normalized name
    for gnss_id, variants in gnss_id_variants.items():
        if lower_name in variants:
            return gnss_id

    # If no match is found, return the original name
    warn_txt = f"Unknown GNSS constellation {name}"
    warnings.warn(warn_txt)
    return name


def check_dataframe(df: pd.DataFrame, required_columns: list, with_warning: bool=True) -> bool:
    """
    Check if all required_columns are in df. If not, returns False.
    :param df: Dataframe to check
    :param required_columns: Liste of required columns
    :param with_warning: Set to False to disable warning
    :return: True if no missing columns else False
    """
    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        if with_warning:
            warnings.warn(f"Missing data : {missing}", UserWarning)
        return False
    return True


def _cache_paths(filepath: Path):
    """
    Build the cache paths for a given source file:
      - csv_path: the cached data itself, human-readable
      - schema_path: sidecar JSON storing the original dtypes
      - lock_path: lock file used for cross-process synchronization

    The cache key includes the file's mtime and size, so the cache is
    automatically invalidated if the source file changes.

    - Generated by Claude ai
    """
    filepath = Path(filepath)
    stat = filepath.stat()
    key = hashlib.sha256(
        f"{filepath.resolve()}-{stat.st_mtime_ns}-{stat.st_size}".encode()
    ).hexdigest()[:16]
    base = filepath.parent / f"{filepath.name.replace('.', '_')}_{key}"
    csv_path = base.with_suffix(".csv")
    schema_path = base.with_suffix(".schema.json")
    lock_path = base.with_suffix(".lock")
    return csv_path, schema_path, lock_path


def _acquire_lock(lock_path: Path, timeout: float = 300, poll: float = 0.2) -> int:
    """
    Open lock_path in exclusive mode (O_CREAT | O_EXCL).
    This "check and create" operation is atomic at the OS/filesystem
    level, so even if multiple processes try it at the exact same
    moment, only one of them will actually get the file descriptor.
    All others get FileExistsError and retry until the lock is free
    or the timeout is reached.

    - Generated by Claude ai
    """
    deadline = time.monotonic() + timeout
    while True:
        try:
            fd = os.open(str(lock_path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            return fd
        except FileExistsError:
            if time.monotonic() > deadline:
                raise TimeoutError(f"Could not acquire lock: {lock_path}")
            time.sleep(poll)


def _release_lock(fd: int, lock_path: Path):
    """Close the file descriptor and remove the lock file. - Generated by Claude ai"""
    os.close(fd)
    try:
        lock_path.unlink()
    except FileNotFoundError:
        pass


def _save_with_schema(df: pd.DataFrame, csv_path: Path, schema_path: Path):
    """
    Save a DataFrame as a plain, human-readable CSV, plus a sidecar
    JSON file storing each column's dtype so it can be restored
    exactly on read (datetime, category, int, float, bool, etc.).

    - Generated by Claude ai
    """
    dtypes = {col: str(dtype) for col, dtype in df.dtypes.items()}

    # Write atomically: tmp file then rename, so no reader ever sees
    # a partially-written file.
    tmp_csv = csv_path.with_suffix(".tmp")
    tmp_schema = schema_path.with_suffix(".tmp")

    # ISO 8601 with microseconds: unambiguous and still human-readable
    df.to_csv(tmp_csv, index=False, date_format="%Y-%m-%dT%H:%M:%S.%f")
    tmp_schema.write_text(json.dumps(dtypes, indent=2))

    tmp_csv.replace(csv_path)
    tmp_schema.replace(schema_path)


def _load_with_schema(csv_path: Path, schema_path: Path) -> pd.DataFrame:
    """Read back a CSV saved with _save_with_schema, restoring exact dtypes. - Generated by Claude ai"""
    dtypes = json.loads(schema_path.read_text())

    # datetime columns must be parsed via parse_dates, not dtype=
    date_cols = [col for col, dt in dtypes.items() if dt.startswith("datetime64")]
    other_dtypes = {col: dt for col, dt in dtypes.items() if col not in date_cols}

    return pd.read_csv(csv_path, dtype=other_dtypes, parse_dates=date_cols)


def fast_parse(filepath: str|Path, parser: Callable, lock_timeout: float = 300) -> pd.DataFrame:
    """
    Parse data from a file, using a CSV + schema cache to avoid re-parsing on every call.

    - filepath: path to the source file to parse
    - parser: callable that takes the filepath and returns a DataFrame
              (e.g. a slow RINEX/georinex parser)
    - lock_timeout: max seconds to wait for the cache lock

    Safe for concurrent calls from multiple threads AND multiple
    separate processes (e.g. pytest-xdist workers): only the first
    caller actually runs `parser`, the others wait for the lock and
    then read the resulting cached CSV.

    If the source file is already a CSV, caching is skipped entirely:
    it is passed straight to `parser` and returned as-is, since there
    is no slow parsing step to avoid.
    """
    filepath = Path(filepath)

    # Source is already a CSV
    if filepath.suffix.lower() == ".csv":
        return parser(filepath)

    csv_path, schema_path, lock_path = _cache_paths(filepath)

    # Fast path: cache already exists, no need to lock anything
    if csv_path.exists() and schema_path.exists():
        return _load_with_schema(csv_path, schema_path)

    fd = _acquire_lock(lock_path, timeout=lock_timeout)
    try:
        # Another process might have finished parsing while we were
        # waiting for the lock, so check again before doing the work
        if csv_path.exists() and schema_path.exists():
            return _load_with_schema(csv_path, schema_path)

        # Slow step: actually parse the source file
        parsed_df = parser(filepath)

        _save_with_schema(parsed_df, csv_path, schema_path)
    finally:
        # Always release the lock, even if parser() raises an exception
        _release_lock(fd, lock_path)

    return _load_with_schema(csv_path, schema_path)

def get_zip_download_url(record_id: str) -> tuple[str, str]:
    """
    Queries the Zenodo API for a given record and returns the download URL
    and filename of the first .zip file found among the record's files.

    :param record_id: Zenodo record ID
    :return: (download_url, filename)
    """
    response = requests.get(f"https://zenodo.org/api/records/{record_id}", timeout=30)
    response.raise_for_status()
    record = response.json()

    for file_entry in record.get("files", []):
        filename = file_entry["key"]
        if filename.lower().endswith(".zip"):
            download_url = file_entry["links"]["self"]
            return download_url, filename

    raise FileNotFoundError(
        f"No .zip file found in Zenodo record {record_id}"
    )


def download_file(url: str, destination: Path, chunk_size: int = 1024 * 1024):
    """
    Streams a file from a URL to a local path, avoiding loading the whole
    file into memory at once (important for large data archives).

    :param url: file URL to download
    :param destination: local path to write the file to
    :param chunk_size: size of each streamed chunk, in bytes
    """
    with requests.get(url, stream=True, timeout=30) as response:
        response.raise_for_status()
        total_size = int(response.headers.get("content-length", 0))
        downloaded = 0

        with open(destination, "wb") as f:
            for chunk in response.iter_content(chunk_size=chunk_size):
                f.write(chunk)
                downloaded += len(chunk)
                if total_size:
                    percent = downloaded / total_size * 100
                    print(f"\rDownloading: {percent:5.1f}%", end="", flush=True)
        print()  # newline after progress bar


def extract_zip(zip_path: Path, target_dir: Path):
    """
    Extracts a ZIP archive into the target directory. Creates the target
    directory if it doesn't already exist.

    :param zip_path: path to the local .zip file
    :param target_dir: directory to extract contents into
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(target_dir)


def download_and_extract(target_dir: Path, record_id: str = "22086421", force: bool = False):
    """
    Downloads the ZIP data archive from a Zenodo record and extracts it
    into target_dir.

    :param record_id: Zenodo record ID
    :param target_dir: directory to extract data into (default: src/data)
    :param force: if False and target_dir already exists and is non-empty,
                   skip the download/extraction
    """
    if target_dir.exists() and any(target_dir.iterdir()) and not force:
        print(f"Data already present in {target_dir}, skipping download.")
        print("Pass force=True to re-download.")
        return

    download_url, filename = get_zip_download_url(record_id)

    # Use a temporary directory so a failed/partial download never leaves
    # a corrupted zip lying around in the repo
    with tempfile.TemporaryDirectory() as tmp_dir:
        zip_path = Path(tmp_dir) / filename
        download_file(download_url, zip_path)
        extract_zip(zip_path, target_dir)


def get_example_data_filepath(data_type: Literal["ephemeris", "raw", "pvt"],
                              rover_type: Literal["fixed", "circular", "urban", "sv"] = "fixed") -> tuple[Path]|None:
    example_data_folderpath = Path(Path(__file__).resolve().parent, "data", "example_data")

    if not example_data_folderpath.exists():
        download_and_extract(example_data_folderpath.parent)

    filepath_dict = {
        "fixed":{
            "ephemeris": ["SEPT2570.23P"],
            "raw": ["SEPT2570.23O"],
            "pvt": ["ground_truth_nmea.txt"],
        },
        "circular": {
            "ephemeris": ["SEPT2570.23P"],
            "raw": ["SEPT2570.23O"],
            "pvt": ["ground_truth_nmea.txt"],
        },
        "urban": {
            "ephemeris": ["SEPT2570.23P"],
            "raw": ["SEPT2570.23O"],
            "pvt": ["ground_truth_nmea.txt"],
        },
        "sv": {
            "ephemeris": ["SkydelRINEX_S_2023257120_120S_SN.rnx",
                          "SkydelRINEX_S_2023257120_600S_EN.rnx",
                          "SkydelRINEX_S_2023257120_1800S_RN.rnx",
                          "SkydelRINEX_S_2023257120_3600S_CN.rnx",
                          "SkydelRINEX_S_2023257120_7200S_GN.rnx"],
            "raw": ["skydel_raw"],
            "pvt": None,
        },
    }

    if rover_type not in filepath_dict.keys():
        return None

    if data_type not in filepath_dict[rover_type].keys():
        return None

    if filepath_dict[rover_type][data_type] is None:
        return None

    filepath_list = []
    for file in filepath_dict[rover_type][data_type]:
        filepath_list.append(Path(os.path.join(example_data_folderpath, rover_type, file)))

    return tuple(filepath_list)


def get_ephemeris(pd_gnss_raw: pd.DataFrame, pd_ephemeris: pd.DataFrame|None = None, ephem_filepath: str|None = None,
                  ignore_warnings: bool = False) -> pd.DataFrame:
    """
    Returns ephemeris dataframe from either an existing dataframe, from a rinex filepath or from the internet.

    :param pd_gnss_raw: GNSS raw dataframe from BITS parser
    :param pd_ephemeris: ephemeris dataframe from BITS parser
    :param ephem_filepath: Path of a rinex nav file
    :param ignore_warnings: Set to True for no warnings
    :return: ephemeris dataframe from BITS parser
    """
    kepler_ephemeris_required_columns = ["time", "time_of_ephemeris", "sqrta", "e", "i0", "idot", "omega0", "omega",
                                         "m0", "omegadot", "deltan", "cuc", "cus", "crc", "crs", "cic", "cis"]
    state_ephemeris_required_columns = ["time", "time_of_ephemeris", "X", "Y", "Z", "dX", "dY", "dZ", "dX2", "dY2", "dZ2"]
    clock_ephemeris_required_columns = ["clock_bias", "clock_drift", "clock_drift_rate"]
    klobuchar_ephemeris_required_columns = ["klo_a0", "klo_a1", "klo_a2", "klo_a3",
                                            "klo_b0", "klo_b1", "klo_b2", "klo_b3"]

    if pd_ephemeris is None:
        if ephem_filepath is None:
            ephem_filepath = ephemeris_from_internet(pd_gnss_raw["time"].iloc[0])
        pd_ephemeris = parse.ephemeris.rinex(ephem_filepath)

    # Check ephemeris dataframe
    if not ignore_warnings:
        clock_ok = check_dataframe(pd_ephemeris, clock_ephemeris_required_columns)
        klo_ok = check_dataframe(pd_ephemeris, klobuchar_ephemeris_required_columns)
        kepler_ok = check_dataframe(pd_ephemeris, kepler_ephemeris_required_columns, with_warning=False)
        state_ok = check_dataframe(pd_ephemeris, state_ephemeris_required_columns, with_warning=False)

        if "gnss_id" in pd_gnss_raw.columns:
            if pd_gnss_raw["gnss_id"].isin(["gal", "gps", "bei"]).any() and not kepler_ok:
                warnings.warn("No kepler parameters found. Galileo, GPS and Beidou are unavailable.")
            if pd_gnss_raw["gnss_id"].isin(["glo"]).any() and not state_ok:
                warnings.warn("No state parameters found. Glonass is unavailable.")

        if not clock_ok:
            warnings.warn("No clock corrections found.")

        if not klo_ok:
            warnings.warn("No Klobuchar parameters found. Ionospheric corrections are not available.")

    return pd_ephemeris


def ephemeris_from_internet(time: np.ndarray) -> str:
    """
    Loads ephemeris from https://cddis.nasa.gov/.
    To be implemented.
    :param time: ephemeris time required (UTC)
    :return: filepath of the downloaded rinex ephemeris file
    """
    raise NotImplementedError("Getting navdata from the internet is not yet implemented. "
                              "Please use a downloaded rinex nav file.")


def get_data_from_ephemeris(pd_raw: pd.DataFrame, pd_ephemeris: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    """
    Retrieves ephemeris data from columns "cols" of pd_ephemeris of corresponding sv_id and closest time from pd_raw.

    :param pd_raw: GNSS raw dataframe from BITS parser
    :param pd_ephemeris: ephemeris dataframe from BITS parser
    :param cols: columns to retrieve from pd_ephemeris
    :return: GNSS raw dataframe with ephemeris data
    """
    raw_sorted = pd_raw.sort_values("time").reset_index(drop=True)
    ephem_sorted = pd_ephemeris.sort_values("time").reset_index(drop=True)

    # Delete already existing "_raw" columns
    dup_cols = [c for c in raw_sorted.columns if c + "_raw" in raw_sorted.columns]
    raw_sorted = raw_sorted.drop(columns=[c + "_raw" for c in dup_cols])

    merged = pd.merge_asof(
        raw_sorted,
        ephem_sorted[["time", "sv_id"] + cols],
        on="time",
        by="sv_id",
        direction="nearest",
        suffixes=("_raw", "")
    )
    return merged
