#!/usr/bin/env python3

"""
Utilities

"""

__authors__ = ("Enki SAURA")
__contact__ = ("esaura@ikosconsulting.com")
__copyright__ = "IKOS"
__date__ = "2025-06-13"
__version__ = "0.0.1"

import pandas as pd
import json
import time
import hashlib
import os
from pathlib import Path
import warnings
from typing import Callable

# Directory where parsed RINEX data is cached as CSV files
CACHE_DIR = Path(".gps_cache")
CACHE_DIR.mkdir(exist_ok=True)


def check_dataframe(df: pd.DataFrame, required_columns: list, with_warning: bool=True) -> bool:
    """
    Check if all required_columns are in df. If not, returns False.
    :param df: Dataframe to check
    :param required_columns: Liste of required columns
    :param with_warning: Set to False to disable warning
    :return: True if no missing columns else False
    """
    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        if with_warning:
            warnings.warn(f"Missing data : {missing}", UserWarning)
        return False
    return True


def _cache_paths(filepath: Path):
    """
    Build the cache paths for a given source file:
      - csv_path: the cached data itself, human-readable
      - schema_path: sidecar JSON storing the original dtypes
      - lock_path: lock file used for cross-process synchronization

    The cache key includes the file's mtime and size, so the cache is
    automatically invalidated if the source file changes.

    - Generated by Claude ai
    """
    filepath = Path(filepath)
    stat = filepath.stat()
    key = hashlib.sha256(
        f"{filepath.resolve()}-{stat.st_mtime_ns}-{stat.st_size}".encode()
    ).hexdigest()[:16]
    base = CACHE_DIR / f"{filepath.stem}_{key}"
    csv_path = base.with_suffix(".csv")
    schema_path = base.with_suffix(".schema.json")
    lock_path = base.with_suffix(".lock")
    return csv_path, schema_path, lock_path


def _acquire_lock(lock_path: Path, timeout: float = 300, poll: float = 0.2) -> int:
    """
    Open lock_path in exclusive mode (O_CREAT | O_EXCL).
    This "check and create" operation is atomic at the OS/filesystem
    level, so even if multiple processes try it at the exact same
    moment, only one of them will actually get the file descriptor.
    All others get FileExistsError and retry until the lock is free
    or the timeout is reached.

    - Generated by Claude ai
    """
    deadline = time.monotonic() + timeout
    while True:
        try:
            fd = os.open(str(lock_path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            return fd
        except FileExistsError:
            if time.monotonic() > deadline:
                raise TimeoutError(f"Could not acquire lock: {lock_path}")
            time.sleep(poll)


def _release_lock(fd: int, lock_path: Path):
    """Close the file descriptor and remove the lock file. - Generated by Claude ai"""
    os.close(fd)
    try:
        lock_path.unlink()
    except FileNotFoundError:
        pass


def _save_with_schema(df: pd.DataFrame, csv_path: Path, schema_path: Path):
    """
    Save a DataFrame as a plain, human-readable CSV, plus a sidecar
    JSON file storing each column's dtype so it can be restored
    exactly on read (datetime, category, int, float, bool, etc.).

    - Generated by Claude ai
    """
    dtypes = {col: str(dtype) for col, dtype in df.dtypes.items()}

    # Write atomically: tmp file then rename, so no reader ever sees
    # a partially-written file.
    tmp_csv = csv_path.with_suffix(".tmp")
    tmp_schema = schema_path.with_suffix(".tmp")

    # ISO 8601 with microseconds: unambiguous and still human-readable
    df.to_csv(tmp_csv, index=False, date_format="%Y-%m-%dT%H:%M:%S.%f")
    tmp_schema.write_text(json.dumps(dtypes, indent=2))

    tmp_csv.replace(csv_path)
    tmp_schema.replace(schema_path)


def _load_with_schema(csv_path: Path, schema_path: Path) -> pd.DataFrame:
    """Read back a CSV saved with _save_with_schema, restoring exact dtypes. - Generated by Claude ai"""
    dtypes = json.loads(schema_path.read_text())

    # datetime columns must be parsed via parse_dates, not dtype=
    date_cols = [col for col, dt in dtypes.items() if dt.startswith("datetime64")]
    other_dtypes = {col: dt for col, dt in dtypes.items() if col not in date_cols}

    return pd.read_csv(csv_path, dtype=other_dtypes, parse_dates=date_cols)


def fast_parse(filepath: str, parser: Callable, lock_timeout: float = 300) -> pd.DataFrame:
    """
    Parse data from a file, using a CSV + schema cache to avoid re-parsing on every call.

    - filepath: path to the source file to parse
    - parser: callable that takes the filepath and returns a DataFrame
              (e.g. a slow RINEX/georinex parser)
    - lock_timeout: max seconds to wait for the cache lock

    Safe for concurrent calls from multiple threads AND multiple
    separate processes (e.g. pytest-xdist workers): only the first
    caller actually runs `parser`, the others wait for the lock and
    then read the resulting cached CSV.

    If the source file is already a CSV, caching is skipped entirely:
    it is passed straight to `parser` and returned as-is, since there
    is no slow parsing step to avoid.
    """
    filepath = Path(filepath)

    # Source is already a CSV
    if filepath.suffix.lower() == ".csv":
        return parser(filepath)

    csv_path, schema_path, lock_path = _cache_paths(filepath)

    # Fast path: cache already exists, no need to lock anything
    if csv_path.exists() and schema_path.exists():
        return _load_with_schema(csv_path, schema_path)

    fd = _acquire_lock(lock_path, timeout=lock_timeout)
    try:
        # Another process might have finished parsing while we were
        # waiting for the lock, so check again before doing the work
        if csv_path.exists() and schema_path.exists():
            return _load_with_schema(csv_path, schema_path)

        # Slow step: actually parse the source file
        parsed_df = parser(filepath)

        _save_with_schema(parsed_df, csv_path, schema_path)
    finally:
        # Always release the lock, even if parser() raises an exception
        _release_lock(fd, lock_path)

    return _load_with_schema(csv_path, schema_path)
